#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_ez_publisher import EzPublisherPlugin

main = Main()
sys.exit(main.main(sys.argv, standalone='rqt_ez_publisher',
                   plugin_argument_provider=EzPublisherPlugin.add_arguments))
